id: I02F47AF8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-17T10:21:19+00:00'
last_modified: '2022-06-15T17:33:23.146922+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29242
  title: འཛམ་གླིང་དུང་ཟླ་དཀར་བོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    BD0B:
      image_group_id: I1KG23298
      title: Volume 1 of 'dzam gling dung zla dkar bo/
      total_pages: 314
      order: 1
      base_file: BD0B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
